# Semgrep configuration for static analysis
# Documentation: https://semgrep.dev/

rules: []

# Paths to scan - now including everything
paths:
  include:
    - "."
  
  exclude:
    - "*.md"  # Exclude markdown documentation
    - "*.txt"  # Exclude text files
    - "*.log"  # Exclude log files
    - ".git/"  # Exclude git directory
    - ".venv/"  # Exclude virtual environments
    - "venv/"
    - "__pycache__/"  # Exclude Python cache
    - "*.pyc"
    - ".terraform/"  # Exclude Terraform cache
    - "*.tfstate"
    - "*.tfstate.backup"

# Use auto configuration for comprehensive scanning
auto_config: true

# Performance settings
max_memory: 2048
timeout: 300
max_file_size: 1000000

# Output settings
verbose: false
output_format: "text"